#!/bin/bash
set -euo pipefail

echo "Clinic SaaS - API Flow Test Placeholder"
echo "======================================="
echo ""
echo "Repo hiện chưa có backend Clinic SaaS runtime hoàn chỉnh."
echo "Không tự tạo JWT/token/endpoint giả để test."
echo ""
echo "Khi services tồn tại, script test full flow cần cover:"
echo "1. API Gateway/BFF health"
echo "2. Tenant resolution bằng domain/subdomain/header/JWT"
echo "3. Owner Super Admin tạo tenant"
echo "4. Clinic Admin bị chặn khi truy cập tenant khác"
echo "5. Template apply mode"
echo "6. Domain verification"
echo "7. Public booking tạo appointment đúng tenant"
echo "8. Notification/event publish nếu workflow có dùng event bus"
echo ""
echo "Dùng .claude command /test-api hoặc rules/backend-testing-rules.md để viết test cụ thể sau khi service có thật."
